#!/usr/bin/env python3
"""Generated by agents-team. Validate a PR, its Goal Issue, and current-head evidence."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path


PR_SECTIONS = [
    "关联任务", "风险等级", "实际改动", "范围偏差", "必须完成项证据",
    "测试门禁", "行为验收", "QA 独立性与结论", "剩余风险", "回滚方式", "失败记录",
]
ISSUE_SECTIONS = ["Goal", "必须完成", "验收门禁", "任务边界", "风险等级", "依赖与阻塞条件", "失败处理与回滚"]
HEADING = re.compile(r"^#{2,6}\s+(.+?)\s*$", re.MULTILINE)
ISSUE_LINK = re.compile(r"\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)\b", re.IGNORECASE)
PLACEHOLDER = re.compile(r"<[^>]+>|待验收|待补充|TODO", re.IGNORECASE)
L3_REQUIRED_FIELDS = ["用户确认", "方案", "回滚"]


def sections(body: str) -> dict[str, str]:
    matches = list(HEADING.finditer(body or ""))
    result: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        result[match.group(1).strip()] = body[match.end():end].strip()
    return result


def scalar(block: str, name: str) -> str:
    match = re.search(rf"(?mi)^\s*(?:[-*]\s+)?{re.escape(name)}\s*[：:]\s*(.+?)\s*$", block)
    return match.group(1).strip() if match else ""


def valid_timestamp(value: str) -> bool:
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return bool(value)


def status_from_labels(labels: list[str]) -> str:
    for label in labels:
        match = re.search(r"\bstatus:([a-z-]+)\b", label, re.IGNORECASE)
        if match:
            return match.group(1).lower()
    return ""


def validate(pr_body: str, issue_body: str, head_sha: str, labels: list[str] | None = None) -> list[str]:
    labels = labels or []
    errors: list[str] = []
    pr = sections(pr_body)
    issue = sections(issue_body)
    for name in PR_SECTIONS:
        if not pr.get(name, "").strip():
            errors.append(f"PR missing section: {name}")
    for name in ISSUE_SECTIONS:
        if not issue.get(name, "").strip():
            errors.append(f"Issue missing section: {name}")
    if not ISSUE_LINK.search(pr_body or ""):
        errors.append("PR must close a numbered Issue")
    if PLACEHOLDER.search(pr_body or ""):
        errors.append("PR contains unresolved placeholders")

    tests = pr.get("测试门禁", "")
    for name in ("gate", "command", "exitCode", "passed", "failed", "skipped", "timestamp", "commitSha", "artifact"):
        if not scalar(tests, name):
            errors.append(f"test evidence missing: {name}")
    if scalar(tests, "exitCode") != "0" or scalar(tests, "failed") != "0":
        errors.append("test evidence is not successful")
    commit_sha = scalar(tests, "commitSha")
    if commit_sha and commit_sha != head_sha:
        errors.append(f"test evidence commitSha {commit_sha} does not match head.sha {head_sha}")
    timestamp = scalar(tests, "timestamp")
    if timestamp and not valid_timestamp(timestamp):
        errors.append("test evidence timestamp is not ISO 8601")
    artifact = scalar(tests, "artifact")
    if artifact and not re.match(r"https://", artifact):
        errors.append("test evidence artifact must be an HTTPS URL")

    risk = pr.get("风险等级", "") + "\n" + issue.get("风险等级", "")
    if re.search(r"\bL[23]\b", risk, re.IGNORECASE):
        qa = pr.get("QA 独立性与结论", "")
        if not re.search(r"独立上下文\s*[：:]\s*是", qa):
            errors.append("L2/L3 QA must use an independent context")
        if not re.search(r"结论\s*[：:]\s*PASS\b", qa, re.IGNORECASE):
            errors.append("L2/L3 QA verdict must be PASS")
        missing_qa = [name for name in ("验收者", "实现上下文", "QA 上下文", "commitSha", "证据") if not scalar(qa, name)]
        if missing_qa:
            errors.append("L2/L3 QA evidence missing: " + ", ".join(missing_qa))
        qa_commit_sha = scalar(qa, "commitSha")
        if qa_commit_sha and qa_commit_sha != head_sha:
            errors.append(f"QA evidence commitSha {qa_commit_sha} does not match head.sha {head_sha}")
        implementation_context = scalar(qa, "实现上下文")
        qa_context = scalar(qa, "QA 上下文")
        if implementation_context and qa_context and implementation_context == qa_context:
            errors.append("QA context must differ from implementation context")
        if status_from_labels(labels) == "pass" and scalar(qa, "验证阶段").lower() != "verify":
            errors.append("PASS status requires explicit verify stage")
    if re.search(r"\bL3\b", risk, re.IGNORECASE):
        for field in L3_REQUIRED_FIELDS:
            if not re.search(rf"(?mi)^\s*{re.escape(field)}\s*[：:]\s*\S+", issue_body or ""):
                errors.append(f"L3 Issue missing required field: {field}")
    return errors


def validate_check_runs(payload: dict, head_sha: str) -> list[str]:
    runs = payload.get("check_runs") or []
    current_runs = [run for run in runs if str(run.get("head_sha") or "") == head_sha]
    if not current_runs:
        return ["GitHub Checks evidence missing for current head"]

    completed = [run for run in current_runs if str(run.get("status") or "") == "completed"]
    if not completed:
        return ["GitHub Checks evidence missing completed runs for current head"]

    errors: list[str] = []
    successful = False
    for run in completed:
        conclusion = str(run.get("conclusion") or "")
        name = str(run.get("name") or "unnamed check")
        if conclusion == "success":
            successful = True
        else:
            errors.append(f"GitHub Check {name} did not pass: {conclusion or 'missing conclusion'}")
    if not successful:
        errors.append("GitHub Checks evidence has no successful completed run for current head")
    return errors


def fetch_issue(repo: str, number: int, token: str) -> str:
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues/{number}",
        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}", "User-Agent": "agents-team-gate"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return str(json.loads(response.read().decode("utf-8")).get("body") or "")
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read linked Issue: {exc}") from exc


def fetch_check_runs(repo: str, head_sha: str, token: str) -> dict:
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/commits/{head_sha}/check-runs",
        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}", "User-Agent": "agents-team-gate"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            payload = json.loads(response.read().decode("utf-8"))
            return payload if isinstance(payload, dict) else {"check_runs": []}
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read GitHub Checks: {exc}") from exc


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", type=Path, required=True)
    parser.add_argument("--issue-body-file", type=Path)
    args = parser.parse_args()
    event = json.loads(args.event.read_text(encoding="utf-8"))
    token = os.environ.get("GITHUB_TOKEN", "")
    pull_request = event.get("pull_request") or {}
    if pull_request.get("draft"):
        print("draft PR: strict contract deferred until ready for review")
        return 0

    pr_body = str(pull_request.get("body") or "")
    head_sha = str((pull_request.get("head") or {}).get("sha") or "")  # head.sha
    labels = [str(label.get("name") or "") for label in (pull_request.get("labels") or []) if isinstance(label, dict)]
    repo = str((event.get("repository") or {}).get("full_name") or os.environ.get("GITHUB_REPOSITORY") or "")
    linked = ISSUE_LINK.search(pr_body)
    if not head_sha or not repo or linked is None:
        errors = ["event is missing repository, head.sha, or linked Issue"]
    else:
        if args.issue_body_file:
            issue_body = args.issue_body_file.read_text(encoding="utf-8")
        else:
            if not token:
                print("Agents-Team gate blocked: GITHUB_TOKEN is required")
                return 1
            try:
                issue_body = fetch_issue(repo, int(linked.group(1)), token)
            except RuntimeError as exc:
                print(f"Agents-Team gate blocked: {exc}")
                return 1
        errors = validate(pr_body, issue_body, head_sha, labels=labels)
        if not token:
            print("Agents-Team gate blocked: GITHUB_TOKEN is required")
            return 1
        try:
            errors.extend(validate_check_runs(fetch_check_runs(repo, head_sha, token), head_sha))
        except RuntimeError as exc:
            print(f"Agents-Team gate blocked: {exc}")
            return 1

    if errors:
        print("Agents-Team PR contract failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print("Agents-Team PR contract passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
